ASP.NET-Core-5-Design-Patterns-main/ASP.NET-Core-5-Design-Patterns-main/C17/src/PageController/Pages/Components/EmployeeCount/EmployeeCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PageController.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PageController.Pages.Components.EmployeeCount
{
    public class EmployeeCountViewComponent : ViewComponent
    {
        private readonly EmployeeDbContext _context;
        public EmployeeCountViewComponent(EmployeeDbContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var count = await _context.Employees.CountAsync();
            return View(new EmployeeCountViewModel(count));
        }
    }
}

ASP.NET-Core-5-Design-Patterns-main/ASP.NET-Core-5-Design-Patterns-main/C17/src/PageController/Pages/Shared/_Layout.cshtml
@using PageController.Pages.Employees

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PageController</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
                asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                asp-fallback-test-class="sr-only" 
                asp-fallback-test-property="position" 
                asp-fallback-test-value="absolute"
                crossorigin="anonymous"
                integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-page="/Index">PageController</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Employees/Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <div class="row pb-3">
            <div class="col-lg-9">
                <main role="main">
                    @RenderBody()
                </main>
            </div>
            <div class="col-lg-3">
                <div class="row row-cols-1">
                    <div class="col mb-4">
                        @*@await Component.InvokeAsync("EmployeeCount")*@
                        @*@await Component.InvokeAsync(typeof(PageController.Pages.Components.EmployeeCount.EmployeeCountViewComponent))*@
                        @*@(await Component.InvokeAsync<PageController.Pages.Components.EmployeeCount.EmployeeCountViewComponent>())*@
                        <vc:employee-count></vc:employee-count>
                    </div>
                    <div class="col mb-4">
                        <vc:employee-count-using-tag-helper></vc:employee-count-using-tag-helper>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PageController - <a asp-area="" asp-page="/Privacy">Privacy</a>
            | <cache>@(new Random().Next())</cache>
            | <cache vary-by-user="true">Hello @this.User.Identity.Name!</cache>
            | <partial name="Employees/_PieceOfUI" model="new PieceOfUIViewModel(true)" />
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>